### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by MegaTheLEGEND** [domesticatedviking/TextyMcSpeechy#12]
Is there a way to run this on windows? All the files are ```.sh```

**Comment by domesticatedviking** [comment]
This is written in shell script so there is no formal support for Windows, but it would definitely work on a Linux virtual machine inside of windows.  WSL might also be an option but I have no experience with it.

**Comment by ssurovich** [comment]
Just wanted to add a comment to anyone else trying or wondering.  This works great under WSL2 Ubuntu with my RTX 4080 laptop.  You dont need to add nVidia GFX drivers since the base nVidia drivers for Windows work with WSL by default. You still the install the toolkit in WSL, but thats easy.
