### ISSUE TITLE
applio only returns .pth and .index files so where is the .ckpt file in steps mentioned using applio?

### ISSUE THREAD

**Issue by mzramle** [domesticatedviking/TextyMcSpeechy#6]
title.

**Comment by domesticatedviking** [comment]
Applio is a voice to voice conversion tool.  The models it uses are only
suitable for converting audio files from one voice to another.   It can be
used to batch convert an existing dataset (audio files + text transcripts
in metadata.csv).

The converted dataset then can be used to produce a text to speech model
with piper via the TTS dojo.

A pretrained piper text to speech model is also needed in addition to the
converted dataset.  Those can be found on huggingface as indicated in the
docs.
